steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mushroom-classification-427315/train-model', '-f', 'mushroom.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mushroom-classification-427315/train-model']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mushroom-classification-427315/predict-model', '-f', 'predict.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mushroom-classification-427315/predict-model']
images:
- 'gcr.io/mushroom-classification-427315/train-model'
- 'gcr.io/mushroom-classification-427315/predict-model'

options:
  logging: CLOUD_LOGGING_ONLY
