name: mushroom_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.8
  - pip
  - pip:
      - -e .
      - -r requirements.txt
      - -r requirements_dev.txt
      - -r requirements_test.txt